name: Lel
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "from_id"
          replace: "sender_id"
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Fix for from_id'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: ѕρι∂у
          commit_user_email: 68327188+sppidy@users.noreply.github.com
          commit_author: ѕρι∂у <68327188+sppidy@users.noreply.github.com>
